### ISSUE TITLE
security risk

### ISSUE THREAD

**Issue by bocajthomas** [WebDevGhost/Login-Page#1]
https://github.com/WebDevGhost/Login-Page/blob/9f809289b08ca28a6c78901c82e0ee708b049700/index.html#L147-L150

Users can see credentials by using the inspect tool. This is a big SECURITY RISK!
you will need to included an api that fetches the Credentials via a server.

**Comment by WebDevGhost** [comment]
> https://github.com/WebDevGhost/Login-Page/blob/9f809289b08ca28a6c78901c82e0ee708b049700/index.html#L147-L150
> 
> Users can see credentials by using the inspect tool. This is a big SECURITY RISK! you will need to included an api that fetches the Credentials via a server.

Thank You for the concern! This is just a simple login page template, actual credentials haven't been added purely for this reason.
